development:
  adapter: "sqlite"
  encoding: "utf8"
  host: "127.0.0.1"
  user: "username"
  password: "password"
  database: "flux_dev"
  port: 1234
  socket: ~
  flags: ~
production:
  adapter: "sqlite"
  encoding: "utf8"
  host: "127.0.0.1"
  user: "username"
  password: "password"
  database: "flux"
  port: 1234
  socket: ~
  flags: ~
